language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
  - "3.2"
  
# command to install dependencies
install: 
  - git submodule update --init --recursive
  - pip -q install cython --install-option="--no-cython-compile"
  - python setup_coolprop.py install
  - sudo conda install numpy matplotlib wxpython h5py
  - python setup.py install # Install PDSim
  
# command to run tests
script: 
  - cd examples
  - python simple_example.py
  - python scroll_compressor.py
  - python piston_expander.py

notifications:
  email:
    recipients:
      - ian.h.bell@gmail.com
    on_success: never # default: change
    on_failure: always # default: always