language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install Cython --use-mirrors
  - pip install numpy scipy
  
# command to run tests
script: 
  - python setup.py install # Install PDSim

notifications:
  email:
    recipients:
      - ian.h.bell@gmail.com
    on_success: never # default: change
    on_failure: always # default: always