name: pdsim_doc_build
dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - IPython
  - cython
  - wxpython
  - pyyaml
  - h5py
  - jupyter
  - nbconvert
  - pip:
    - CoolProp
    - glob2
    - cx_Freeze