channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - h5py
  - cython
  - pip
  - coolprop
#  - wxpython
  - pip:
    - "git+git://github.com/ibell/pdsim.git"
