channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - h5py
  - cython
#  - wxpython
  - pip:
    - CoolProp
    - Cython
    - "git+git://github.com/ibell/pdsim.git"
